import AppSkeleton from '@/components/AppSkeleton';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const TimerCalendar = dynamic(
  () => import('../components/TimerCalendarContainer'),
  {
    ssr: false,
    loading: () => <AppSkeleton />
  }
);

export default function Calendar() {
  return (
    <>
      <Head>
        <title>Calendar | In Time Life Calendar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="max-w-screen-2xl px-6 lg:px-12 mx-auto flex flex-1 flex-col items-center justify-center w-full">
        <TimerCalendar />
      </section>
    </>
  );
}
