import AppSkeleton from '@/components/AppSkeleton';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const DynamicCalendar = dynamic(
  () => import('../components/CalendarContainer'),
  {
    ssr: false,
    loading: () => <AppSkeleton />
  }
);

export default function Calendar() {
  return (
    <>
      <Head>
        <title>In Time Life Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="max-w-screen-2xl px-6 lg:px-12 m-auto w-full">
        <DynamicCalendar />
      </section>
    </>
  );
}
