import Head from 'next/head';
import dynamic from 'next/dynamic';
import AppSkeleton from '@/components/AppSkeleton';

const App = dynamic(() => import('../components/AppContainer'), {
  ssr: false,
  loading: () => <AppSkeleton />
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Get Started | In Time Life Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="max-w-screen-2xl px-6 lg:px-12 m-auto w-full">
        <App />
      </section>
    </>
  );
}
